:global:
  componentName: cloud-portal
  githubUrl: https://github.com/appuio/component-cloud-portal
  feature_goldenTests: true
  testMatrix:
    key: instance
    entries:
      - defaults

docs/antora.yml:
  name: cloud-portal
  title: cloud-portal
.github/workflows/test.yaml:
  test_makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
