= Parameters

The parent key for all of the following parameters is `cloud_portal`.

== `namespace`

[horizontal]
type:: string
default:: `appuio-cloud-portal`

The namespace in which to deploy this component.


== `release_name`

[horizontal]
type:: string
default:: `cloud-portal`

The name under which the helm chart is deployed.

== `images.cloud-portal`

[horizontal]
type:: dict
default:: See https://github.com/appuio/component-cloud-portal/blob/master/class/defaults.yml[`class/defaults.yml`]

The container image to use for the cloud portal deployment.
The contents of this parameter are passed to the Helm chart in value `image`.


== `charts.cloud-portal.source`

[horizontal]
type:: string
default:: `https://charts.appuio.ch`

The Helm repository for the `cloud-portal` Helm chart.


== `charts.cloud-portal.version`

[horizontal]
type:: string
example:: https://github.com/appuio/component-cloud-portal/blob/master/class/defaults.yml[See `class/defaults.yml`]

The version to use for the `cloud-portal` Helm chart.


== `helm_values`

[horizontal]
type:: object

Allows setting additional values for the Cloud Portal Helm chart.


== Example

[source,yaml]
----
cloud_portal:
  helm_values:
    replicaCount: 2
    route:
      enabled: true
      host: portal.appuio.example
    portal:
      config:
        issuer: https://portal.appuio.example/auth/realms/appuio-cloud
        clientId: appuio-control-api
      env:
        APPUIO_API: https://portal.appuio.example/
----
